services:
  psh-ohs:
    image: ghcr.io/destinationhome/game-ohs:latest
    container_name: game-ohs
    user: "1002:1002"
    restart: unless-stopped
    environment:
      - "HOST=0.0.0.0"
      - "PORT=8080"
      - "RUST_LOG=${LOG_LEVEL:-info}"
      - "DB_URI=mongodb://mongo:27017/psh-ohs"
      - "TELEMETRY_ENABLED=true"
      - "TELEMETRY_ENDPOINT=http://172.17.0.1:4317"
    ports:
      - "30080:8080"
    volumes:
      - /srv/destinationhome/public/ohs/webassets:/app/webassets:ro
      - /srv/destinationhome/private/ohs/static:/app/static
    networks:
      - ohs-network

networks:
  ohs-network:
    external: true
    name: ohs-network
