use mongodb::bson::Bson;
use ranged_integers::Ranged;

/// Max account ID is 8 digits, because Home might panic if it exceeds that.
const MAX_ACCOUNT_ID: i128 = 99_999_999;

/// Cast type for account IDs in the database.
type AccountIdType = u64;

/// Unique identifier for the account.
///
/// This is an integer that is automatically generated by
/// the database when a new account is created.
///
/// It should not exceed 8 digits, or Home might panic.
#[derive(Clone, Copy, Debug, Hash, PartialEq, Eq)]
pub struct AccountId(Ranged<0, MAX_ACCOUNT_ID>);
impl AccountId {
    pub fn generate() -> Self {
        let id = rand::random_range(0..=MAX_ACCOUNT_ID);
        Self(Ranged::new(id).expect("Generated account ID is out of range"))
    }
}

impl serde::Serialize for AccountId {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        let id: AccountIdType = self.0.into();
        id.serialize(serializer)
    }
}

impl<'de> serde::Deserialize<'de> for AccountId {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let id = AccountIdType::deserialize(deserializer)?;
        let ranged = Ranged::new(id as i128)
            .ok_or_else(|| serde::de::Error::custom("Invalid account ID"))?;

        Ok(Self(ranged))
    }
}

impl From<AccountId> for Bson {
    fn from(val: AccountId) -> Self {
        let id: AccountIdType = val.0.into();
        Self::Int64(id as i64)
    }
}

impl std::fmt::Display for AccountId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let id: AccountIdType = self.0.into();
        write!(f, "{}", id)
    }
}
